client_id: 3MVG9QDx8IX8nP5S1j8K8NIx4STLrGn4D8v.aHxOmhsuSOjOpWBDlchwj4Pc0CEJxertYaQcIO52yzWAd_6eL
client_secret: 4821612639868928006

version: 23.0
debugging: true

username: [your username]
password: [your password]