source 'http://rubygems.org'

gem 'rack'
gem 'rails', '3.1.0'
gem 'minitest'

gem 'haml'
gem 'haml-rails'

gem 'pg'  # for heroku
gem 'sqlite3' #prototype db

gem 'databasedotcom'
#leverage te databasedotcom rails helper gem
gem 'databasedotcom-rails'

gem 'jquery-rails'
gem 'httparty'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', "  ~> 3.1.0"
  gem 'coffee-rails', "~> 3.1.0"
  gem 'uglifier'
end

group :test do
  # Pretty printed test output
  gem 'cucumber'
  gem 'gherkin'
  gem 'rspec'
  gem 'turn', :require => false
end

group :development do
  gem 'ruby_parser'
  gem 'hpricot'
end
